FinalMvcProject/Models/RoomAllocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FinalMvcProject.Models
{
    public class RoomAllocation
    {
        public int Id { set; get; }

        [Required(ErrorMessage = "Please Enter a Department")]
        public int DepartmentId { set; get; }
        public virtual Department Department { set; get; }

        [Required(ErrorMessage = "Please Enter a Couse")]
        public int CourseId { set; get; }
        public virtual Course Course { set; get; }

        [Required(ErrorMessage = "Please Enter a Room")]
        public int RoomId { set; get; }
        public virtual Room Room { set; get; }

        [Required(ErrorMessage = "Please Enter a Day")]
        public int DayId { set; get; }
        public virtual Day Day { set; get; }

        [Display(Name = "From")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string From { get; set; }

        [Display(Name = "To")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        public string To { get; set; }

        public bool Status { get; set; }
    }
}

FinalMvcProject/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalMvcProject.Models;

namespace FinalMvcProject.Controllers
{
    public class CourseController : Controller
    {
        private UniversityDbContext db = new UniversityDbContext();

        // GET: /Course/
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Department).Include(c => c.Semester);
            return View(courses.ToList());
        }


        // GET: /Course/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name");
            return View();
        }

        // POST: /Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="CourseId,Code,Name,Credit,Description,DepartmentId,SemesterId")] Course course)
        {
            course.Status = true;
            var list = from p in db.Semesters where p.SemesterId == course.SemesterId select p;
            foreach (var item in list)
            {
                course.SemName = item.Name;
            }
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                TempData["Success"] = "Course Added Successfully!!";
                return RedirectToAction("Create");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
            ViewBag.SemesterId = new SelectList(db.Semesters, "SemesterId", "Name", course.SemesterId);
            return View(course);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult IsUserCodeAvailable(string code)
        {
            var course = db.Courses.FirstOrDefault(x => x.Code == code);
            if (course != null)
            {
                return Json("Course Code is already registered ", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult IsUserNameAvailable(string name)
        {
            var course = db.Courses.FirstOrDefault(x => x.Name == name);
            if (course != null)
            {
                return Json("Course Name is already registered ", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FinalMvcProject/Controllers/RoomAllocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalMvcProject.Models;

namespace FinalMvcProject.Controllers
{
    public class RoomAllocationController : Controller
    {
        private UniversityDbContext db = new UniversityDbContext();


        public string Unallocate()
        {
            var rooms = from p in db.RoomAllocations where p.Status.Equals(true) select p;
            foreach (var roomAllocation in rooms)
            {
                roomAllocation.Status = false;
                db.RoomAllocations.AddOrUpdate(roomAllocation);
            }
            db.SaveChanges();
            return "All Rooms Are Unallocated";
        }


        public ActionResult Index()
        {
            var roomallocations = db.RoomAllocations.Include(r => r.Department).Include(r => r.Course).Include(r => r.Room).Include(r => r.Day);
            return View(roomallocations.ToList());
        }

       
        // GET: /RoomAllocation/Create

        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            ViewBag.CourseId = new SelectList("", "CourseId", "Code");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name");
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Name");
            return View();
        }

        //
        // POST: /RoomAllocation/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomAllocation roomallocation)
        {

            Room room = db.Rooms.Find(roomallocation.RoomId);
            Course course = db.Courses.Find(roomallocation.CourseId);
            Day day = db.Days.Find(roomallocation.DayId);

            roomallocation.Status = true;


            if (ModelState.IsValid)
            {

                int givenfrom, givenEnd;

                try
                {
                    givenfrom = ConvertTimetoInt(roomallocation.From);
                }
                catch (Exception anException)
                {
                    if (TempData["ErrorMessage3"] == null)
                    {
                        TempData["ErrorMessage1"] = anException.Message;
                    }
                    TempData["ErrorMessage4"] = TempData["ErrorMessage3"];
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);

                }

                try
                {
                    givenEnd = ConvertTimetoInt(roomallocation.To);
                }
                catch (Exception anException)
                {
                    if (TempData["ErrorMessage3"] == null)
                    {
                        TempData["ErrorMessage2"] = anException.Message;
                    }
                    TempData["ErrorMessage5"] = TempData["ErrorMessage3"];
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }

                if (givenEnd < givenfrom)
                {
                    TempData["Error"] = "Class Must Should be Started at 24 hours";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }
                if (givenEnd == givenfrom)
                {
                    TempData["Error"] = "Class Must Should be Started at 24 hours";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }

                if ((givenfrom < 0) || (givenEnd >= (24 * 60)))
                {
                    TempData["Message"] = " 24 hours--format HH:MM";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }

                List<RoomAllocation> overLapList = new List<RoomAllocation>();

                var DayRoomAllocationList =
                db.RoomAllocations.Include(c => c.Course).Include(d => d.Day).Include(r => r.Room).Where(r => r.RoomId == roomallocation.RoomId && r.DayId == roomallocation.DayId)
                    .ToList();

                foreach (var aDayroomAllocation in DayRoomAllocationList)
                {
                    //int OverlapFrom = 0;
                    //int OverlapEnd = 0;
                    //RoomAllocation overlap =new RoomAllocation();
                    if (aDayroomAllocation.Status.Equals(true))
                    {
                        int DbFrom = ConvertTimetoInt(aDayroomAllocation.From);
                        int DbEnd = ConvertTimetoInt(aDayroomAllocation.To);

                        if (
                                ((DbFrom <= givenfrom) && (givenfrom < DbEnd))
                                || ((DbFrom < givenEnd) && (givenEnd <= DbEnd))
                                || ((givenfrom <= DbFrom) && (DbEnd <= givenEnd))
                            )
                        {
                            overLapList.Add(aDayroomAllocation);
                        }
                    }

                }
                if (overLapList.Count == 0)
                {

                    db.RoomAllocations.Add(roomallocation);
                    db.SaveChanges();
                    TempData["Message"] = "Room : " + room.Name + " " + "Allocated "
                    + " for course : " + course.Code + " From " + roomallocation.From
                    + " to " + roomallocation.To + " on " + day.Name;
                }
                else
                {
                    string message = "Room : " + room.Name + " Overlapped With : ";
                    foreach (var anOverlappedRoom in overLapList)
                    {
                        int dbFrom = ConvertTimetoInt(anOverlappedRoom.From);
                        int dbEnd = ConvertTimetoInt(anOverlappedRoom.To);

                        string overlapStart, overlapEnd;

                        if ((dbFrom <= givenfrom) && (givenfrom < dbEnd))
                            overlapStart = roomallocation.From;
                        else
                            overlapStart = anOverlappedRoom.From;

                        if ((dbFrom < givenEnd) && (givenEnd <= dbEnd))
                            overlapEnd = roomallocation.To;
                        else
                            overlapEnd = anOverlappedRoom.To;
                        message += " Course : " + anOverlappedRoom.Course.Code + " Start Time : "
                            + anOverlappedRoom.From + " End Time : "
                            + anOverlappedRoom.To + " Overlapped from : ";
                        message += overlapStart + " To " + overlapEnd;
                    }

                    TempData["Overlapping"] = message + " on " + day.Name;

                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }
                //}

                return RedirectToAction("Create");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", roomallocation.DepartmentId);

FinalMvcProject/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalMvcProject.Models;

namespace FinalMvcProject.Controllers
{
    public class StudentController : Controller
    {
        private UniversityDbContext db = new UniversityDbContext();

        // GET: /Student/
        public ActionResult Index()
        {
            var students = db.Students.Include(s => s.Department);
            return View(students.ToList());
        }

        // GET: /Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: /Student/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            return View();
        }

        // POST: /Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="StudentId,Name,Email,ContactNo,Date,Address,DepartmentId,RegistrationId")] Student student)
        {
            if (ModelState.IsValid)
            {
                student.RegistrationId = GenarateRegistationId(student);

                db.Students.Add(student);
                db.SaveChanges();
                TempData["reg"] = student.Name + ". RegistrationId is : " + student.Name;
                ViewBag.RegId = student.Name + ". RegistrationId is : " + student.Name;
               
                return RedirectToAction("Details", new { id = student.StudentId });
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentCode", student.DepartmentId);
            return View(student);
        }

        private string GenarateRegistationId(Student student)
        {
            int id = db.Students.Count(
                    s => (s.DepartmentId == student.DepartmentId) &&
                         (s.Date.Year == student.Date.Year)) + 1;
            Department aDepartment = db.Departments.FirstOrDefault(d => d.DepartmentId == student.DepartmentId);
            string registrationId = aDepartment.Code + "-" + student.Date.Year + "-";
            return registrationId + id.ToString("000");

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult IsEmailUnique(string email)
        {
            var student = db.Students.FirstOrDefault(x => x.Email == email);
            if (student != null)
            {
                return Json("Student Email is already registered ", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FinalMvcProject/Views/Shared/_CourseInfo.cshtml
<div id="CourseInfo">
    <table>
        <tr>
            <td>Code : </td>
            <td>@ViewBag.Code</td>
        </tr>
        <tr>
            <td>Credit  : </td>
            <td>@ViewBag.Credit</td>
        </tr>
    </table>
</div>

FinalMvcProject/Views/Shared/_CourseStatus.cshtml
@model IEnumerable<FinalMvcProject.Models.Course>

@if (Model != null)
{
    <table class="table table-bordered text-center">
        <h3>Course Information</h3>
        <tr>
            <th style="text-align: center;">
                Course code</th>
            <th style="text-align: center;">
                Course Name
            </th>
            <th style="text-align: center;">
                Semester
            </th>
            <th style="text-align: center;">
                Assigned To
            </th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SemName)
                </td>
                <td>
                    @if (item.AssignTo != null)
                    {
                        @Html.DisplayFor(modelItem => item.AssignTo)
                    }
                    @if (item.AssignTo == null)
                    {
                        item.AssignTo = "Not Assigned";
                        @Html.DisplayFor(modelItem => item.AssignTo)
                    }
                </td>

            </tr>
        }

    </table>
}
<div style="color: darkgoldenrod"><h3>@ViewBag.NotAssigned</h3></div>

FinalMvcProject/Views/Shared/_FillteredTeacher.cshtml
@if (ViewBag.TeacherId != null)
{
    @Html.DropDownList("TeacherId", string.Empty)

}

FinalMvcProject/Views/Shared/_FilteredCourse.cshtml
@if (ViewBag.CourseId != null)
{
    @Html.DropDownList("CourseId", string.Empty)
}

FinalMvcProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Final Mvc Project</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("University Management System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Department <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Department", "Create", "Department")</li>
                            <li>@Html.ActionLink("View All Departments", "Index", "Department")</li>

                        </ul>
                    </li>
                    
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Course<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Course", "Create", "Course")</li>
                            <li>@Html.ActionLink("Add Teacher", "Create", "Teacher")</li>
                            <li>@Html.ActionLink("Course Assign To Teacher", "Create", "AssignCourse")</li>
                            <li>@Html.ActionLink("View Course Statics", "ViewCourseStatus", "AssignCourse")</li>
                        </ul>
                    </li>

                    
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Student<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register Student", "Create", "Student")</li>
                            <li>@Html.ActionLink("Enroll In a Course", "Create", "EnrollCourse")</li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Room<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Allocate ClassRooms", "Create", "RoomAllocation")</li>
                            <li>@Html.ActionLink("View Class Schedule Info", "RoomAllocationView", "RoomAllocation")</li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Result<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Save Student Result", "Create", "ResultEntry")</li>
                            <li>@Html.ActionLink("View Result", "ViewResult", "ResultEntry")</li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Unassign Or Unallocate<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Unassign All Courses", "Unassign", "AssignCourse")</li>
                            <li id="unallocate">@Html.ActionLink("Unallocate All ClassRooms", "Unallocate", "RoomAllocation")</li>
                        </ul>
                    </li>
                    

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="font-size: 25px;">&copy; @DateTime.Now.Year - Robust Storm Team</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

FinalMvcProject/Views/Shared/_ResultInformation.cshtml
@model IEnumerable<FinalMvcProject.Models.EnrollCourse>
           
@*<p>

    <input type="submit" value="Make PDF" class="btn btn-primary" />
</p>*@
           
@if (Model != null)
{
    <table class="table table-bordered text-center">
        <tr>
            <th style="text-align: center;">
                Course Code
            </th>
            <th style="text-align: center;">
                Course Name
            </th>
            <th style="text-align: center;">
                Grade
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>
                <td>
                    @if (item.GradeName != null)
                    {
                        @Html.DisplayFor(modelItem => item.GradeName)
                    }
                    @if (item.GradeName == null)
                    {
                        item.GradeName = "Empty";
                        @Html.DisplayFor(modelItem => item.GradeName)
                    }

                </td>
            </tr>
        }
    </table>
}
<div style="color: darkgoldenrod"><h3>@ViewBag.NotEnrolled</h3></div>

FinalMvcProject/Views/Shared/_RoomAllocationView.cshtml
@model IEnumerable<FinalMvcProject.Models.Course>
           
<table class="table table-bordered text-center">
    <tr>
        <th style="text-align: center;">
            Course Code
        </th>
        <th style="text-align: center;">
            Name/Title
        </th>
        <th style="text-align: center;">
            Schedule Info
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var anAllocatedRoom in item.RoomAllocationList)
                {
                    <b>Room:</b>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.Room.Name)
                    <i>,</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.Day.Name)
                    <i>,</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.From)
                    <i>-</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.To)
                    <b><i>;</i></b>
                }
                @if (item.RoomAllocationList.Count == 0)
                {
                    <i>Unscheduled</i>
                }
            </td>

        </tr>
    }

</table>
<div style="color: darkgoldenrod"><h3>@ViewBag.NoCourse</h3></div>

FinalMvcProject/Views/Shared/_StudentInformation.cshtml
<div id="StudentInfo">
    <table>
        <tr>
            <td>Name  : </td>
            <td>@ViewBag.Name</td>
        </tr>
        <tr>
            <td>Email  : </td>
            <td>@ViewBag.Email</td>
        </tr>
        <tr>
            <td>Department  : </td>
            <td>@ViewBag.Dept</td>
        </tr>
        
    </table>
    
    
</div>

FinalMvcProject/Views/Shared/_TeachersCreditInfo.cshtml
<div id="TeacherInfo">
    <table>
        <tr>
            <td>Credit to be taken  : </td>
            <td>@ViewBag.Credit</td>
        </tr>
        <tr>
            <td>Remaining Credit  : </td>
            <td>@ViewBag.RemainingCredit</td>
        </tr>

    </table>
</div>